### ISSUE TITLE
Week 0 - Aadit Gupta Review Ticket

### ISSUE THREAD

**Issue by aaditgupta21** [aaditgupta21/koolskool#5]
- [X] Navigates Tech Talk, Test Prep notes and plans
- [X] Navigates Data Structures work, GitHub for Code, Replit for runtime, or alternatives
- [X] Navigates Create Task work for College Board work, GitHub for Code, runtime instructions (required if taking test)

**Evidence**
- [Github Pages](https://aaditgupta21.github.io/csp-notes)
- [Repl.it Runtime](https://replit.com/@aaditgupta21/csp-notes)
- [Github Code](https://github.com/aaditgupta21/csp-notes/tree/main/code)
- [Week 0 TPT Github Page](https://aaditgupta21.github.io/csp-notes/prep/5.1-5.2)
- [Group Review Ticket](https://github.com/aaditgupta21/koolskool/issues/4)

**Comment by lleosunn** [comment]
GitHub page for Test Prep study, requiring 5.1, 5.2 notes and actions 1/1
Aadit had all 5.1 and 5.2 notes and actions.
GitHub page that documents Data Structures project, using code snippets for key learnings, and links to GitHub for code and Replit for runtime 1/1
Aadit had a link to his GitHub code and replit.
GitHub page that documents intended Create Task project for College Board, snippets, and links to Runtime 1/1
The create task plan had all requirements.
